region            = "us-east-1"
vpc_name          = "my-vpc"
ec2_name          = "my-ec2"
ami_id            = "ami-xxxxxxxx"  # Replace with your AMI ID
instance_type     = "t2.micro"
key_name          = "your-ssh-key-name"  # Replace with your SSH key name
rds_name          = "my-rds"
db_instance_class = "db.t2.micro"
db_storage        = 20
db_name           = "mydatabase"
db_username       = "admin"
db_password       = "password123"  # RDS password (sensitive)
